mysite/blog/urls.py
from django.urls import path,include
from . import views
from django.contrib import admin

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='list'),
    path('<int:blog_id>', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('delete', views.delete, name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/signup/', user_views.signup, name='signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE) #회원이 사라지면 관련된 데이터도 지워 달라는 것
    title = models.CharField(max_length=200)
    content = models.TextField()
    thumbnail = models.ImageField(upload_to='Blog/thumbnail/')
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

mysite/user/models.py
from django.db import models

# Create your models here.

mysite/blog/forms.py
from django import forms
from blog.models import Blog

# class BlogUploadForm(forms.Form):
#     title = forms.CharField(max_length=200)
#     content = forms.CharField
#     thumbnail = forms.ImageField

class BlogUploadForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields = '__all__'
        exclude = ['user']

mysite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog
from .forms import BlogUploadForm

def index(request):
    blog_list = Blog.objects.filter(is_published=True)
    context = {
        'blog_list': blog_list
    }
    return render(request, 'blog/index.html', context)

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk = blog_id)
    context = {
        'blog': blog
    }
    return render(request, 'blog/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = BlogUploadForm(request.POST, request.FILES)

        if form.is_valid():
            blog = form.save(commit=False)
            blog.user=request.user
            blog.save()
            # title = form.cleaned_data['title']
            # content = form.cleaned_data['content']
            # thumbnail = form.cleaned_data['thumbnail']
            #
            # Blog.objects.create(
            #     title=title,
            #     content=content,
            #     thumbnail=thumbnail,
            #     is_published=True,
            # )
            return redirect('blog:list')
        else:
            return render(request, 'blog/create.html', {
                'form': form
            })
    else:
        form = BlogUploadForm()
        return render(request, 'blog/create.html',{
            'form': form
        })


def delete(request):
    if request.method == 'POST':
        blog_pk = request.POST.get('blog_pk','')
        blog = Blog.object.get(pk=blog_pk)
        if blog.user== request.user:
            blog.delete()
        return redirect('blog:list')
    else:
        return redirect('blog:list')

mysite/user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('blog:list')

    else:
        form = UserCreationForm()
        return render(request, 'registration/signup.html',{'form': form})

mysite/templates/blog/create.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="container">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit">
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

mysite/templates/blog/detail.html
{% extends 'layout.html' %}

{% block content %}
<div class ="row">
    <div class="container"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
            <h1>{{ blog.title }}</h1>
            <p>작성자 - {{ blog.user.username }}</p>
            <p>작성일 - {{ blog.created_date }}</p>
            <p>{{ blog.content }}</p>
            <p>
                <img src="{{ blog.thumbnail.url }}" alt="">
            </p>

            <p>
                <a href="{% url 'blog:list' %}">목록</a>
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </p>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
{% endblock %}

mysite/templates/blog/index.html
{% extends 'layout.html' %}

{% block content %}


<div class ="col">
    <div class="container">
        <div class="section-header">
            <h1 class="section-title wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">Blog List</h1>

        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
            {% for blog in blog_list %}
            <tr>
                <td><a href="{% url 'blog:detail' blog.pk %}">{{ blog.title }}</a></td>
                <td>
                    <form action="{% url 'blog:delete' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="blog_pk" value="{{ blog.pk }}">
                        <button type="submit"></button>


                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="row-md-6">


            <p>
                 <a href="{%url 'blog:create' %}">글쓰기</a>
              </p>
        </div>

</div>
</div>
{% endblock %}

mysite/templates/footer.html
<div class ="panel panel-default">

    <div class="panel-footer">footer</div>
</div>

mysite/templates/header.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'blog:list' %}">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        {% if request.user.is_authenticated %}

          <li><a href="" disabled>{{ request.user.username }}님</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
      </ul>
    </div><!— /.navbar-collapse —>
  </div><!— /.container-fluid —>
</nav>

mysite/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>블로그</title>
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
</head>

<body>
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}


</body>
</html>